version: '3.8'

services:
  db:
    image: postgres:15
    container_name: ms_inventory_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ms_inventory
    ports:
      - "6432:5432" 
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: ms_inventory_redis
    ports:
      - "7379:6379" 

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ms_inventory_app
    environment:
      PORT: 4002
      NODE_ENV: production
      DATABASE_URL: postgres://postgres:password@db:5432/ms_inventory
      PRODUCT_SERVICE_URL: http://ms_catalog:4001/api/products
      REDIS_URL: redis://redis:6379
      CACHE_EXPIRY: 3600
    ports:
      - "5002:4002"
    depends_on:
      - db
      - redis

volumes:
  db_data: