version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: ms-inventory_postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "7432:5432"
    volumes:
      - postgres_data_inventory:/var/lib/postgresql/data
    networks:
      - microservicios-red
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5


  db-init:
      image: postgres:15
      container_name: ms-inventory_db-init
      depends_on:
        postgres:
          condition: service_healthy
      command: >
        psql -U postgres -h postgres -c "CREATE DATABASE \"ms-inventory\";"
      environment:
        PGPASSWORD: 1234
      networks:
        - microservicios-red
  # Redis
  redis:
    image: redis:7
    container_name: ms-inventory_redis
    ports:
      - "8379:6379"
    networks:
      - microservicios-red

  # Node.js Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ms-inventory_app
    ports:
      - "5002:4002"
    environment:
      DATABASE_URL: postgres://postgres:1234@postgres:5432/ms-inventory
      PRODUCT_SERVICE_URL: http://ms-catalog_app:4001/api/product
      PORT: 4002
      NODE_ENV: production
      REDIS_URL: redis://redis:6379
      CACHE_EXPIRY: 3600
      RETRY_ATTEMPTS: 3
      RETRY_DELAY: 1000
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_RETRY_DELAY: 2000  
      DB_POOL_MAX: 5
      DB_POOL_MIN: 1
      DB_POOL_IDLE: 600000
      DB_POOL_ACQUIRE: 30000
      PRODUCT_SERVICE_TIMEOUT: 5000
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
    command: npm run dev
    networks:
      - microservicios-red

volumes:
  postgres_data_inventory:

networks:
  microservicios-red:
    external: true